language: node_js
node_js:
 - 'stable'
cache:
  directories:
    - node_modules
install: [ "npm install"]
addons:
  code_climate:
    repo_token: 9b2b54cc957142a8374b974636097694d3ba3dc1f007524fd255095d0e8e5efe
  coveralls:
    coveralls: KQ1TKPuCXpuFNdhpEtcnMaAROLVJIYQmh
after_script:
  - ./node_modules/.bin/gulp coveralls
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info